(function() {
    const retards_title = [
        "1.8.9",
        "1.7.10",
        "1.21.1", 
        "1.21.4", 
        "1.21.8",
        "1.12.2",
        "1.16.5",
        "1.20.1",
        "zenith recode",
        "monoton",
        "fabric", "forge",
        "exp 3.1",
        "exp 2.0",
        "intellij",
        "minced",
        "targetesp",
        "funtime",
        "spookytime","spokytime",
        "evaware",
        "relake recode",
        "exosware",
        "catlavan",
        "nursultan",
        "wexside",
        "expensive",
        "elysion",
        "mcp",
        "grim",
        "pulse visual",
        "labymod",
        "rich client",
        "autobuy",
        "clickgui",
        "mineblaze",
        "dexland",
        "item scroller",
        "blockoverlay",
        "cristalix",
        "slimeworld",
        "holyworld",
        "reallyworld",
        "фантайм",
        "ancientxray",
        "shoreline",
        "cakeworld",
        "noweb",
        "lonygrief",
        "minced",
        "zenithclient",
        "dekoclient",
        "rassvetnightly",
        "danqrebirth",
        "monoton",
        "expensiveupgrade",
        "nightdlc",
        "shitpaste",
        "amoral",
        "dreamcore",
        "relake",
        "excellentomni",
        "spartaclient",
        "desteny",
        "astralisbeta",
        "waileent",
        "essence",
        "komarudlc",
        "dimasik",
        "litkaclient",
        "vredux",
        "nuckerdlc",
        "liorclient",
        "kimadlc",
        "celestial recode",
        "venus",
        "hynix",
        "spectra",
        "zovchik",
        "mantance",
        "lunoclient",
        "damage",
        "foxclient",
        "rockstar",
        "zaharov",
        "seasonreloadd",
        "vegaline",
        "multiware",
        "verist",
        "haruka",
        "excellent recode",
        "wiksi",
        "awesome project",
        "excellent upgrade",
        "newcode",
        "hachclient",
        "koshkadlc",
        "wirent",
        "zexis",
        "neverhook",
        "excellent",
        "expensive 3.1",
        "wissend",
        "exclusive",
        "expensive 2.0",
        "wild",
        "killaura",
        "килка", "киллаура", "киллку", "киллка",
        "slothac",
        "elytratarget",
        "nurik",
        "rogalik",
        "teslacraft",
        "ителидж", "интелидж", // самые тупорылые ебланы кто пишут так
        "deslight",
        "автобай",
        "минцед",
        "ватермарка",
    ];

    function removeAds(banword_list) {
        const tabGroups = document.querySelectorAll('div.tabGroup-content');

        tabGroups.forEach(tabGroup => {
            const listItems = tabGroup.querySelectorAll('li.item');
            
            listItems.forEach(li => {
                for (let ban_words of banword_list) {
                    if (li.textContent.toLowerCase().includes(ban_words)) {
                        li.remove();
                        console.log("detected title (" + li.textContent + ")");
                    }
                }
            });
        });
    }

    removeAds(retards_title);
})();

